### ISSUE TITLE
Cherno Autumn Todo List

### ISSUE THREAD

**Issue by davidcit646** [7CavArma3Dev/7Cav-Alive-Altis#215]
**People Involved**
1. Centeno
2. Macmillan
3. Citarelli.D

**To-Do**
- [x] Complete the addition of ACE Slideshows.

- [x] Add functional respawns.

- [x] Add resupply script to aircraft carrier.

- [x] Add custom strongpoints.

- [x] Test vehicle respawns.

- [x] Set CRAM installations on carrier / destroyer to disabled, leaving only the missile defense.

**Comment by JoyfulJP** [comment]
Commenting on for assignment

**Comment by JoyfulJP** [comment]
Please assign

**Comment by davidcit646** [comment]
@JoyfulJP add your strongpoints and get it off to MacMillan;

@MacMillan-M I showed Centeno how to make ALiVE, so he is sending you a rough draft. I want you to look it over and fix any imperfections. After he sends you the mission file, we are awaiting final iteration testing and script additions.

Let's get this out ASAP gentlemen.

**Comment by davidcit646** [comment]
Completed.
